
on: [workflow_dispatch]
name: ACI_Deploy_Build and Deploy a Node.JS App to Azure Container Instances

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTAILS }}
        
        #- uses: azure/docker-login@v1
        #  with:
        #    login-server: contoso.azurecr.io
        #    username: ${{ secrets.REGISTRY_USERNAME }}
        #    password: ${{ secrets.REGISTRY_PASSWORD }}
        #- run: |
        #    docker build . -t contoso.azurecr.io/nodejssampleapp:${{ github.sha }}
        #    docker push contoso.azurecr.io/nodejssampleapp:${{ github.sha }}
        
        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: AjayKale_RG
            dns-name-label: ajaykalecontainer
            image: nginx
            cpu: 1
            memory: 0.5
            name: contoso-container
            location: 'east us'
