# File: .github/workflows/Azure_login_action.yml

on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - uses: azure/login@v1
        with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
        az webapp list --query “[?state==‘Running’]”

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: |
        az webapp list --query "[?state=='Running']"
