
# File: AzureLoginSample.yml

on: [workflow_dispatch]

name: AzureLoginSample

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout repo
      uses: actions/checkout@v2
      
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTAILS}}
        enable-AzPSSession: true 
     
     
        
