# File: Azure_login_action

on: [workflow_dispatch]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: windows-latest
    steps:
    - run: echo 'My name is' 
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTAILS }}
    - run: |
        az webapp list --query "[?state=='Running']"
  
