
# File: azure-get-keyvault-secrets.yml

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
    - uses: actions/checkout@master
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTAILS }} 
    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "CLI-KeyVault-Testing"
        secrets: 'mySecret'  # comma separated list of secret keys that need to be fetched from the Key Vault 
      id: myGetSecretAction
        
