name: Run Azure Login PS
on: workflow_dispatch

jobs: 
  az-login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: 'Az CLI login with subscription'
        #uses: azure/login@v1
        uses: Azure/login@oidc-support
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - run: |
          az account show
          pwd 
          cat ~/.azure/accessTokens.json
      - uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzContext
            Get-AzVM -ResourceGroupName "akshaya-tests"
          azPSVersion: "latest"
          failOnStandardError: true
