name: specific_CLI.yml

on: [workflow_dispatch]

jobs:

  build-and-deploy:
    runs-on: 222-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTAILS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:        
        azcliversion: latest        
        inlineScript: |
          az account show
          az storage -h
