# sql-deploy.yml
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTAILS }}
    - uses: azure/sql-action@v1
      with:
        server-name: 'mysqlserver-ak.database.windows.net'
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        dacpac-package: './Database.dacpac'
