# sql-deploy.yml
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    
    #CLI Dependency Testing - START
    - uses: actions/setup-python@v2
      with:
          python-version: '3.x'
           
    - run: |
        $CWD = Convert-Path .
        echo $CWD
        python --version
        python -m venv oidc-venv
        . .\oidc-venv\Scripts\Activate.ps1
        python -m pip install -q --upgrade pip
        echo "started installing cli beta" 
        pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
        echo "***************installed cli beta*******************" 
        echo "$CWD\oidc-venv\Scripts" >> $env:GITHUB_PATH
    
    #CLI Dependency Testing - END
    
    #- uses: azure/login@v1
    - uses: Azure/login@oidc-support
      with:
        creds: ${{ secrets.AZURE_CREDENTAILS }}
    - uses: azure/sql-action@v1
      with:
        server-name: 'mysqlserver-ak.database.windows.net'
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        sql-file: './sql_action.sql'
